accounts/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='homePage'),
    path('register/', views.register_type, name='registerType'),
    path('register/customerRegister/', views.customer_register, name='customerRegister'),
    path('register/driverRegister/', views.driver_register, name='driverRegister'),
    path('login/', views.login_page, name='loginPage'),
    path('logout/', views.logout_user, name='logout'),
    path('user/', views.user_page, name='userBookingsList'),  # list the user bookings
    path('driver_trips/', views.available_trips, name='driverTrips'),  # list the  bookings for driver
    path('booking/', views.booking_view, name='tripBooking'),  # book a trip
    path('update_booking/<str:pk>/', views.update_booking_view, name='updateBooking'),  # update a booking
    path('delete_booking/<str:pk>/', views.customer_delete_booking_view, name='deleteBooking'),  # delete a booking
    path('accept_booking/<str:pk>/', views.accept_booking_driver, name='acceptBookingDriver'),  # accept a booking by driver
    path('cancel_booking/<str:pk>/', views.cancel_booking_driver, name='cancelBookingDriver'),  # cancel a booking by driver
    path('customer_details/', views.edit_customer_profile, name='customerDetails'),
    path('driver_details/', views.edit_driver_profile, name='driverDetails'),
]

taxiapp/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls'))

]

accounts/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class Customer(models.Model):
    customer = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    phone = models.CharField(max_length=20, default='Your Phone')
    address = models.CharField(max_length=200,  default='Your Address')
    town = models.CharField(max_length=200,  default='Your Town')
    county = models.CharField(max_length=200,  default='Your County')
    postcode = models.CharField(max_length=20,  default='Your Postcode')
    payment_method = models.CharField(max_length=20,  default='Your Payment Method')

    def __str__(self):
        return f'{self.customer.username} Profile'


class Driver(models.Model):
    driver = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    reg_No = models.CharField(max_length=20,  default='Your Registration Plate')
    availability = models.BooleanField('Available', default=True)

    def __str__(self):
        return self.driver.username


class Booking(models.Model):
    STATUS = (
        ('Pending', 'Pending'),
        ('In Progress', 'In Progress'),
        ('Finished', 'Finished'),
    )
    customer = models.ForeignKey(Customer, null=True, on_delete=models.SET_NULL)
    driver = models.ForeignKey(Driver, null=True, on_delete=models.SET_NULL)
    date_booked = models.DateTimeField(auto_now_add=True, null=True)
    start_address = models.CharField(max_length=200, null=True)
    destination_address = models.CharField(max_length=200, null=True)
    date = models.DateField('Trip Date', null=True)
    time = models.TimeField('Trip Time', null=True)
    status = models.CharField(max_length=15, choices=STATUS, null=True, default='Pending')
    paid = models.BooleanField(default=False)

    def __str__(self):
        return "Booking "+str(self.id)

    def get_absolute_url(self):
        return reverse('userPage')

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm

from .models import *


class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            'username', 'first_name',
            'last_name', 'email',
            'password1', 'password2',
        ]


class DriverInfoForm(forms.ModelForm):
    class Meta:
        model = Driver
        fields = [
            'reg_No',
        ]


class CustomerEditForm(ModelForm):
    class Meta:
        model = Customer
        fields = [
            'phone', 'address', 'town',
            'county', 'postcode', 'payment_method',
        ]


class DateInput(forms.DateInput):
    input_type = 'date'


class TimeInput(forms.TimeInput):
    input_type = 'time'


class TripBookingForm(forms.ModelForm):

    date = forms.DateField(widget=DateInput)
    time = forms.TimeField(widget=TimeInput)

    class Meta:
        model = Booking
        fields = [

            'start_address', 'destination_address',
            'date', 'time',
        ]

accounts/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group
from django.shortcuts import render

from .decorators import *
from .forms import *


def home(request):
    return render(request, 'accounts/dashboard.html')


@unauthenticated_user
def customer_register(request):  # is going to be a customer registration page
    form = RegistrationForm()
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            group = Group.objects.get(name='CUSTOMER')
            user.groups.add(group)
            Customer.objects.create(customer=user, )

            messages.success(request, 'Account was created for ' + username)
            return redirect('loginPage')
    context = {'form': form}
    return render(request, 'accounts/register.html', context)


def register_type(request):
    return render(request, 'accounts/signupType.html')


@unauthenticated_user
def driver_register(request):
    form = RegistrationForm()
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            group = Group.objects.get(name='DRIVER')
            user.groups.add(group)
            Driver.objects.create(driver=user, )
            messages.success(request, 'Account was created for ' + username)
            return redirect('loginPage')
    context = {'form': form}
    return render(request, 'accounts/register.html', context)


@unauthenticated_user
def login_page(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('homePage')
        else:
            messages.info(request, 'Username OR password is incorrect')

    context = {}
    return render(request, 'accounts/login.html', context)


def logout_user(request):
    logout(request)
    return redirect('homePage')


# lists the logged-in user bookings
@login_required(login_url='loginPage')
@allowed_user(allowed_roles=['CUSTOMER'])
def user_page(request):
    bookings = request.user.customer.booking_set.all()

    pending = bookings.filter(status='Pending').count()
    in_progress = bookings.filter(status='In Progress').count()
    finished = bookings.filter(status='Finished').count()

    context = {'bookings': bookings, 'pending': pending,
               'in_progress': in_progress, 'finished': finished}
    return render(request, 'accounts/user.html', context)


@login_required(login_url='loginPage')
@allowed_user(allowed_roles=['CUSTOMER'])
def booking_view(request):
    if request.method == 'POST':
        form = TripBookingForm(request.POST)
        if form.is_valid():
            trip = form.save(commit=False)
            trip.customer = request.user.customer  # logged-in User
            trip.save()
            return redirect('userBookingsList')
    else:
        form = TripBookingForm()
    context = {'form': form}
    return render(request, 'accounts/booking_form.html', context)


@login_required(login_url='loginPage')
@allowed_user(allowed_roles=['CUSTOMER'])
def update_booking_view(request, pk):
    booking = Booking.objects.get(id=pk)

    if request.method == 'POST':
        form = TripBookingForm(request.POST, instance=booking)
        if form.is_valid():
            form.save()
            return redirect('userBookingsList')
    else:
        form = TripBookingForm(instance=booking)
    context = {'form': form}
    return render(request, 'accounts/booking_form.html', context)


@login_required(login_url='loginPage')
@allowed_user(allowed_roles=['CUSTOMER'])
def customer_delete_booking_view(request, pk):
    booking = Booking.objects.get(id=pk)

    if request.method == 'POST':
        booking.delete()
        return redirect('userBookingsList')
    context = {'booking': booking}
    return render(request, 'accounts/customer_delete_booking.html', context)


@login_required(login_url='loginPage')
@allowed_user(allowed_roles=['CUSTOMER'])
def edit_customer_profile(request):
    if request.method == 'POST':
        form = CustomerEditForm(request.POST, instance=request.user.customer)
        if form.is_valid():
            form.save()
            messages.success(request, f'The user information has been updated successfully')
            return redirect('homePage')
    else:
        form = CustomerEditForm(instance=request.user.customer)
    context = {'form': form}
    return render(request, 'accounts/edit_customer_profile.html', context)


@login_required(login_url='loginPage')
@allowed_user(allowed_roles=['DRIVER'])
def edit_driver_profile(request):
    if request.method == 'POST':
        form = DriverInfoForm(request.POST, instance=request.user.driver)
        if form.is_valid():
            form.save()
            messages.success(request, f'The user information has been updated successfully')
            return redirect('homePage')
    else:
        form = DriverInfoForm(instance=request.user.driver)
    context = {'form': form}
    return render(request, 'accounts/edit_customer_profile.html', context)


@login_required(login_url='loginPage')
@allowed_user(allowed_roles=['DRIVER'])
def available_trips(request):
    bookings_pending = Booking.objects.filter(status='Pending').all()
    driver = request.user.driver
    bookings_in_progress = Booking.objects.filter(status='In Progress', driver=driver).all()
    bookings_finished = Booking.objects.filter(status='Finished', driver=driver).all()

    context = {'bookings_pending': bookings_pending,
               'bookings_in_progress': bookings_in_progress,
               'bookings_finished': bookings_finished}
    return render(request, 'accounts/available_trip_driver.html', context)


@login_required(login_url='loginPage')
@allowed_user(allowed_roles=['DRIVER'])
def accept_booking_driver(request, pk):
    booking = Booking.objects.get(id=pk)
    driver = request.user.driver
    if request.method == 'POST':
        booking.driver = driver
        booking.status = 'In Progress'
        booking.save()
        return redirect('driverTrips')

    context = {'booking': booking}
    return render(request, 'accounts/accept_booking_driver.html', context)


@login_required(login_url='loginPage')
@allowed_user(allowed_roles=['DRIVER'])
def cancel_booking_driver(request, pk):
    booking = Booking.objects.get(id=pk)
    cancel = None
    if request.method == 'POST':
        booking.driver = cancel
        booking.status = 'Pending'
        booking.save()
        return redirect('driverTrips')
    context = {'booking': booking}
    return render(request, 'accounts/cancel_booking_driver.html', context)

accounts/templates/accounts/accept_booking_driver.html
{% extends 'accounts/main.html' %}
{% block content %}

<p>Are you sure you want to accept the booking?</p>

<form action="{% url 'acceptBookingDriver' booking.id %}" method="POST">
    {% csrf_token %}
    <a href="{% url 'driverTrips' %}">No</a>

    <input type="submit" value="Yes, accept the booking">
</form>

{% endblock content %}

accounts/templates/accounts/available_trip_driver.html
{% extends 'accounts/main.html' %}
{% block content %}


<!--			Available trips         -->
			<h2 class = "booking">Available Trips</h2>

			<table class="booking-table">
				<tr>
					<th>PickUp Address</th>
					<th>Destination</th>
					<th>Date</th>
					<th>Time</th>
					<th>Status</th>
					<th></th>

				</tr>

				{% for booking in bookings_pending %}

				<tr>
					<td>{{booking.start_address}}</td>
					<td>{{booking.destination_address}}</td>
					<td>{{booking.date}}</td>
					<td>{{booking.time}}</td>
					<td><b><i class="material-icons" style="font-size: auto; vertical-align: middle; margin-right: 10px;">	history</i>{{booking.status}}...</b></td>
					<td><a href="{% url 'acceptBookingDriver' booking.id %}">Accept Trip</a></td>



				</tr>

				{% endfor %}

			</table>

<!--			Accepted trips         -->

			<h2 class="booking">Accepted Trips</h2>

			<table class="booking-table">
				<tr>
					<th>PickUp Address</th>
					<th>Destination</th>
					<th>Date</th>
					<th>Time</th>
					<th>Status</th>
					<th>Paid</th>
					<th></th>

				</tr>

				{% for booking in bookings_in_progress %}

				<tr>
					<td>{{booking.start_address}}</td>
					<td>{{booking.destination_address}}</td>
					<td>{{booking.date}}</td>
					<td>{{booking.time}}</td>
					<td>{{booking.status}}</td>
					{% if booking.paid == True %}
						<td><i class="material-icons" style="font-size:auto;">check_circle</i></td>
					{% else %}
						<td><i class="material-icons" style="font-size:auto;">radio_button_unchecked</i></td>
					{% endif %}
					<td><a href="{% url 'cancelBookingDriver' booking.id %}">Cancel Trip</a></td>



				</tr>

				{% endfor %}

			</table>


		<!--			Finished trips         -->
		<div class="card card-body">
			<h2 class="booking">Finished Trips</h2>

			<table class="booking-table">
				<tr>
					<th>PickUp Address</th>
					<th>Destination</th>
					<th>Date</th>
					<th>Time</th>
					<th>Status</th>
					<th>Paid</th>

				</tr>

				{% for booking in bookings_finished %}

				<tr>
					<td>{{booking.start_address}}</td>
					<td>{{booking.destination_address}}</td>
					<td>{{booking.date}}</td>
					<td>{{booking.time}}</td>
					<td>{{booking.status}}</td>
					{% if booking.paid == True %}
						<td><i class="material-icons" style="font-size:auto;color: green;">check_circle</i></td>

					{% endif %}

				</tr>

				{% endfor %}

			</table>


{% endblock content %}

accounts/templates/accounts/booking_form.html
{% extends 'accounts/main.html' %}
{% load static %}
{%block content%}
<div class="edit-wrapper">
    <h2>Make a booking</h2>
<form method="POST">
    {% csrf_token %}
    <input type="text" name="start_address" maxlength="200" required="" id="id_start_address" placeholder="Pickup Adress...">
    <input type="text" name="destination_address" maxlength="200" required="" id="id_destination_address" placeholder="Destination Adress..."><br>
    <input type="date" name="date" required="" id="id_date">
    <input type="time" name="time" required="" id="id_time"><br>
     <input type="submit" name="Book">

</form>
</div>
{% endblock content %}

accounts/templates/accounts/cancel_booking_driver.html
{% extends 'accounts/main.html' %}
{% block content %}

<p>Are you sure you want to cancel the booking?</p>

<form action="{% url 'cancelBookingDriver' booking.id %}" method="POST">
    {% csrf_token %}
    <a href="{% url 'driverTrips' %}">No</a>

    <input type="submit" value="Yes, cancel the booking">
</form>

{% endblock content %}

accounts/templates/accounts/customer_delete_booking.html
{% extends 'accounts/main.html' %}
{% block content %}

<p>Are you sure you want to delete the booking?</p>

<form action="{% url 'deleteBooking' booking.id%}" method="POST">
    {% csrf_token %}
    <a href="{% url 'userBookingsList' %}">No</a>

    <input type="submit" value="Yes, cancel the booking">
</form>

{% endblock content %}

accounts/templates/accounts/dashboard.html
{% extends 'accounts/main.html' %}
{% load static %}

{% block content %}
    <h1>RICHKIN dashboard</h1>
    <h2>At Richkin, we believe that every person needs to reach their destinaton
        at anytime with high quality services at a fair price. We're trying to make you happy by offering you
        a safe enviroment to travel which meets the highest standards in the transports industry.

    </h2>
{% endblock content %}

accounts/templates/accounts/edit_customer_profile.html
{% extends 'accounts/main.html' %}
{% block title %}Customer Profile{% endblock %}
{% block content %}


<div class="edit-wrapper">
    <h2 style="color: #303030; text-align: center;">Edit Personal Information</h2>

    <form action="" method="POST">
        {% csrf_token %}

        {{form.phone}}

        {{form.address}}

        {{form.town}}

        {{form.county}}

        {{form.postcode}}

        {{form.payment_method}}

        {{form.reg_No}}


<input type="submit" name="Update" value="Update">
    </form>
</div>


{% endblock content %}

accounts/templates/accounts/login.html
{% extends 'accounts/main.html' %}
{% block title %}Customer Registration{% endblock title %}

{% block content %}

<div class="login-form">

    <form method="POST" autocomplete="off">
        {% csrf_token %}
        <div>
            <i class="material-icons" style="font-size: auto;color:orange; float: left;">account_box</i>
                <input type="text" name="username" autofocus="" autocapitalize="none" autocomplete="off"
                    maxlength="150" required="" id="id_username" placeholder="User Name...">
        </div>

    <div>
        <i class="material-icons" style="color:orange; float: left;">lock</i><br>
            <input type="password" name="password" autocomplete="off" required="" id="id_password" placeholder="Password...">
        </div>

    <input type="submit" value="Login">


    </form>


    {% for message in messages %}
        <p id="messages">{{message}}</p>
    {% endfor %}
    </div>
    <div class="mt-4">
        <div class="d-flex justify-content-center links">
            Don't have an account? <a href="{% url 'registerType' %}" class="ml-2">Sign Up</a>
        </div>
    </div>
</div>

{% endblock content %}

accounts/templates/accounts/main.html
{% load static %}
{% load auth_extras %}
<!DOCTYPE html>

<head>
    <title>Website</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script>
        // Get the modal
        var modal = document.getElementById('id01');

        // When the user clicks anywhere outside of the modal, close it
        window.onclick = function(event) {
          if (event.target == modal) {
            modal.style.display = "none";
          }
        }

        // Get the modal
        var modal2 = document.getElementById('id02');

        // When the user clicks anywhere outside of the modal, close it
        window.onclick = function(event) {
          if (event.target == modal2) {
            modal2.style.display = "none";
          }
        }
        </script>
</head>

<body>
    <nav>
        <ul class="left-nav-opt">
            <li><a href="/"><i class="material-icons" style="font-size:auto;color:white;margin-right: 10px;">view_module</i>HOME</a></li>
        </ul>
        <ul class="right-nav-opt">

            {% if user.is_authenticated %}
                {% if request.user|has_group:"CUSTOMER" %}
                    <li><a href="{% url 'customerDetails' %}"><i class="material-icons menu-icons">person_pin</i>Customer Profile</a></li>
                {% elif request.user|has_group:"DRIVER" %}
                <li><a href="{% url 'driverTrips' %}"><i class="material-icons menu-icons">near_me</i>My Trips</a></li>
                    <li><a href="{% url 'driverDetails' %}"><i class="material-icons menu-icons">	person_pin</i>Driver Profile</a></li>
                {% endif %}

                {% if request.user|has_group:"CUSTOMER" %}
                <li><a href="{% url 'tripBooking' %}"><i class="material-icons menu-icons">add_location</i>Get a ride</a></li>
                    <li><a href="{% url 'userBookingsList' %}"><i class="material-icons menu-icons">directions_car</i>My Bookings</a></li>
                {% endif %}
            {% endif%}
            {% if user.is_authenticated %}
                <li><a href="{% url 'logout' %}"><i class="material-icons menu-icons">	phonelink_erase</i>LOGOUT {{ user.get_username }}</a></li>
            {% else %}
                <li><a href="{% url 'loginPage' %}"><i class="material-icons" style="font-size:auto;color:white;margin-right: 5px;">vpn_key</i>LOGIN</a></li>
                <li><a href="{% url 'registerType' %}"><i class="material-icons" style="font-size:auto;color:white;margin-right: 5px;">person_add</i>SIGN UP</a></li>
            </ul>
            {% endif%}
    </nav>

    <div class="bg">
        <div class="child">
            {% block content %}
             <div class="container">
                <h1 class="front">Need a ride ?</h1>
                <div class="front-links"><a href="#">Take a ride</a></div>

            {% endblock content %}
            <div style="text-align: center; margin-top: 30px;"> <i class="material-icons" style="font-size:60px; opacity: 0.2;">&#xe52d;</i></div>

        </div>
    </div>





</body>
</html>

accounts/templates/accounts/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
  <a class="navbar-brand" href="#">RICHKIN</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        {% if user.is_authenticated %}
        {% if user.groups %}
        <a class="nav-link" href="#">Ride <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="#">Drive <span class="sr-only">(current)</span></a>
      </li>
    </ul>
  </div>
  <span></span>
</nav>

accounts/templates/accounts/register.html
{% extends 'accounts/main.html' %}
{% load static %}

{% block content %}

<h3>Register</h3>

<div class="reg-form">

<form method="POST" action="">
    {% csrf_token %}
    <input type="text" name="username" maxlength="150" autofocus="" required="" id="id_username" placeholder="User Name...">
    <input type="text" name="first_name" maxlength="150" id="id_first_name" placeholder="First Name...">
    <input type="text" name="last_name" maxlength="150" id="id_last_name" placeholder="Last Name...">
    <input type="email" name="email" maxlength="254" id="id_email" placeholder="E-Mail...">
    <input type="password" name="password1" autocomplete="off" required="" id="id_password1" placeholder="Passoword...">
    <input type="password" name="password2" autocomplete="off" required="" id="id_password2" placeholder="Retype Password...">
    <input type="submit" name="Create account" value="REGISTER">
    <div class="mt-4">
        <div class="d-flex justify-content-center links">
            Already have an account? <a href="{% url 'loginPage' %}" class="ml-2">Sign In</a>
        </div>
    </div>
</form>
</div>
{% endblock content %}

accounts/templates/accounts/signupType.html
{% extends 'accounts/main.html' %}

{% block title %} Registration{% endblock title %}

{% block content %}

<div class="reg-type">
    <a href="{% url 'driverRegister' %}" class="reg-link"><i class="material-icons" style="font-size: 100%; margin-right: 15px;">local_taxi</i>Be a driver </a>
    <a href="{% url 'customerRegister' %}" class="reg-link"><i class="material-icons" style="font-size: 100%; margin-right: 15px;">my_location</i>Need a ride ?</a>
</div>


{% endblock content %}

accounts/templates/accounts/user.html
{% extends 'accounts/main.html' %}
{% block content %}
<a class="btn btn-primary btn-sm btn-block" href="{% url 'tripBooking' %}">Book a Trip</a>
	<table class="booking-table">
		<tr>
		<th>Pickup Adress</th>
		<th>Destination Adress</th>
		<th>Date</th>
		<th>Time</th>
		<th>Status</th>
		<th></th>
		<th></th>
		</tr>
				{% for booking in bookings %}

				<tr>
					<td>{{booking.start_address}}</td>
					<td>{{booking.destination_address}}</td>
					<td>{{booking.date}}</td>
					<td>{{booking.time}}</td>
					<td><b><i class="material-icons" style="font-size: auto; vertical-align: middle; margin-right: 10px;">	history</i>{{booking.status}}...</b></td>

					<td>
						<button onclick="document.getElementById('id02').style.display='block'" style="background-color: yellowgreen;">Update</button>

						<div id="id02" class="modal">
							<span onclick="document.getElementById('id02').style.display='none'" class="close" title="Close Modal">×</span>

								<form  class="modal-content" action="{% url 'updateBooking' booking.id %}" method="POST">
									{% csrf_token %}
							  			<div class="container">
									<h1>Update a booking.</h1>

									<input type="text" name="start_address" maxlength="200" required="" id="id_start_address" placeholder="Pickup Adress...">
									<input type="text" name="destination_address" maxlength="200" required="" id="id_destination_address" placeholder="Destination Adress..."><br>
									<input type="date" name="date" required="" id="id_date">
									<input type="time" name="time" required="" id="id_time"><br>
									<input type="submit" name="edit" value="Update">

										</div>
								</form>
						  </div>
					</td>

					<td>
						<button onclick="document.getElementById('id01').style.display='block'" style="background-color: tomato;">Delete</button>

						<div id="id01" class="modal">
							<span onclick="document.getElementById('id01').style.display='none'" class="close" title="Close Modal">×</span>

								<form  class="modal-content" action="{% url 'deleteBooking' booking.id %}" method="POST">
									{% csrf_token %}
							  <div class="container">
								<h1>Delete booking.</h1>
								<p>Are you sure you want to delete your trip ?</p>

								<div class="clearfix">
								  <button type="button" onclick="document.getElementById('id01').style.display='none'" class="cancelbtn">Cancel</button>
									<input type="submit" value="Delete" onclick="document.getElementById('id01').style.display='none'">
								  </form>

								  <!-- <button type="button" onclick="document.getElementById('id01').style.display='none'" class="deletebtn">Delete</button> -->
								</div>
							  </div>
							</form>
						  </div>
					</td>
				  </tr>

				{% endfor %}

	</table>

{% endblock content %}